### PR TITLE
Single command option

### PR DESCRIPTION
**Pull request by jdsumsion**
I want Commandable to not try to parse multiple commands because some of the args that I want to pass to the first command conflict with the names of another command.

Commandable, please don't be greedy.

### CODE REVIEW

**Comment by mikbe** [comment]
I like what you've done. Will incorporate this when I refactor the code, probably this weekend.

**Comment by mikbe** [comment]
The more I look at this the more I think there could be a better way to do it. With this change if you want to be able to accept command names as parameters you **must only** accept single command parameters.

When I wrote the parser I was trying to solve the problem of greedy parameter lists and I did it the simplest way possible. I want to revisit this and see if I can't think of something better. The problem is I can't think of a way to handle greedy method parameters **and** avoid using some kind of command indicator like "-" and I would rather just have the developer name their methods so they don't conflict with parameters.

**Comment by jdsumsion** [comment]
I saw your patch to the README, and as I reread the README (carefully, this time), it seems that the intent of the argument parsing implementation was quite a bit different than what I was thinking.

Now I see that the argument model you support is basically a Rubyesque, non-paren, non-comma-separated arg-to-arg invocation style.

I'm writing a git subcommand as a ruby gem (@jdsumsion/git-ged).  As a git subcommand, my gem's CLI would be very much out of place if it were to insist on the kind of CLI style that commandable supports.  What I need for my program is a traditional "-dash -options + args" commandline, but without all the OptionParser non-DRYness.

This pull request definitely doesn't make any more sense to me.  So I'll close it.

If I can, I'll try to put an alternative, opt-in arg parsing scheme in place that push exactly two arguments to each command method:
1. an "options" hash with defaults populated for that command, and
2. a "remaining args" list

See https://gist.github.com/1621592 for a starting point for how I want to parse the argv => options + args.

What do you think of this?  Would this alternative arg parsing scheme be something that you would think of including in commandable (as a non-default option)?

**Comment by mikbe** [comment]
Hmmm, I'm not crazy about that level of complexity. It really gets away from the spirit of simplifying command line usage for the end user and developer alike. There's no reason you can't fork it and bend it to your needs though.

I am working of a sub command system though so you can have `app command subcommand arguments`.

**Comment by jdsumsion** [comment]
Turns out what I was really looking for is the cli gem:
- https://rubygems.org/gems/cli

Although it doesn't have explicit support for 'subcommands', it won't be too hard to pre-scan the ARGV and pull the command name out, and look things up in a global hash.

**Comment by mikbe** [comment]
Cool, looks good. Also the CLI gem has been around for a while so it pretty mature; Commandable isn't even to a 1.0 yet.

**Pull request closed without merging**
